module.exports = {
  content: ['./**/*.php', './**/*.html', './**/*.js'],
  theme: {
    extend: {
      colors: {
        'green-1': '#01a24d',
        'green-2': '#00bf5a',
        'green-3': '#007437',
        white: '#fff',
        black: '#111',
        'grey-1': '#f1f1f5',
        'grey-2': '#bbb',
        yellow: '#ffd96a',
        pink: '#f9aae8',
        'red-1': '#f33',
        'red-2': '#cf0101',
        color: '#898989',
        grassy: '#0c432f',
        bedge: '#faf7f2',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        second: ['Inter Tight', 'sans-serif'],
      },
      screens: {
        'xs': '345px',
        'sm': '480px',
        'md': '599px',
        'lg': '767px',
        'xl': '920px',
        '2xl': '1023px',
        '3xl': '1199px',
        '4xl': '1365px',
        '5xl': '1430px',
        '6xl': '1640px',
        '7xl': '1705px',
      },
    },
  },
  plugins: [],
};
